### ISSUE TITLE
Fix timestamp when going offsite

### ISSUE THREAD

**Issue by elikimchi** [PSCS-Coding/Attendance_System#219] opened 2015-06-05 14:38 UTC
@Appleguy15, U know what I'm talkin bout.

AM, PM!

**Comment by nwarmenh** [comment] 2015-06-09 17:54
I saw this on the screen when it happened, but I am unable to reproduce the issue.  How can it be made to happen?

**Comment by badtzmaru** [comment] 2015-09-11 18:09
until this resurfaces, i am closing this issure

**Closed by badtzmaru** 2015-09-11 18:09 UTC
