### ISSUE TITLE
Offsite stats (leaderboards) not appearing on production

### ISSUE THREAD

**Issue by nwarmenh** [PSCS-Coding/Attendance_System#143] opened 2015-03-17 22:47 UTC
It's a big blank page.

**Comment by Appleguy15** [comment] 2015-03-17 22:48
I will work in that once I get home.

**Comment by Appleguy15** [comment] 2015-03-18 00:50
@nwarmenh  I need @badtzmaru to fix this one. The problem is with the function "calculateStats" in function.php on line <b><i>453</i></b>. Here is a picture:
![screen shot 2015-03-17 at 5 49 03 pm](https://cloud.githubusercontent.com/assets/6172938/6700621/f8e56252-cccd-11e4-807a-5c7db9b22bb4.png)

**Comment by badtzmaru** [comment] 2015-03-18 00:53
It must have been merged incorrectly with groups... I tested it on
production before we added groups...

**Comment by Appleguy15** [comment] 2015-03-18 00:59
@badtzmaru I was testing it on MAMP and it worked until I pulled the updated database from production.

**Comment by badtzmaru** [comment] 2015-03-18 14:26
I think its time to change broke this... Maybe view reports is broken as
well?

**Comment by badtzmaru** [comment] 2015-03-18 14:28
Hmm. View reports still works and they use the same code... I dont know
what's up with this but I will look at it first slot today...

**Comment by Appleguy15** [comment] 2015-03-18 14:30
Ok.

**Comment by badtzmaru** [comment] 2015-03-18 16:14
i think its fixed now. i opened a pull request for the fix.

**Closed** 2015-03-18 19:37 UTC
Labels: bug
